[package]
name = "client"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
sawfish-client = { path = "../../client" }

[features]
experimental-xcb = ["sawfish-client/experimental-xcb"]
